In [ ]:
# Assignment 1 by Aiswarya Lenin

In [ ]:
import numpy as np

In [ ]:
##Creating a list and converting it to a numpy array
list = [1,2,3,4,5]

In [ ]:
a = np.array(list)
a

array([1, 2, 3, 4, 5])

In [ ]:
#Creating a matrix and converting it to a numpy array
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
np.array(matrix1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
##Making a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

matrix2 = np.arange(1,19,2)
matrix2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [ ]:
matrix2.reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [ ]:
##Creating a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

arr = np.random.randint(0,10,10)
arr

array([7, 2, 4, 8, 5, 2, 7, 0, 6, 4])

In [ ]:
##Creating numpy array => [1,2,3,4,5] and convert it to 2D array with 5 rows

array = np.array([1,2,3,4,5])
array.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
##Print the shape of the above created array
array.shape

(5,)

In [ ]:
##Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

nparray = np.random.randint(1,88,10)
nparray


array([41, 18, 77, 70, 66, 61, 19,  9, 77, 72])

In [ ]:
nparray[2]

77

In [ ]:
nparray[3]

70

In [ ]:
nparray[8]

77

In [ ]:
##Print alternate elements of that array

nparray[0:10:2]

array([41, 77, 66, 19, 77])

In [ ]:
##Change last 3 elements into 100 using broadcasting and print

nparray[7:10] = 100
nparray

array([ 41,  18,  77,  70,  66,  61,  19, 100, 100, 100])

In [ ]:
##Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.
arr2 = np.arange(25)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
matrix3 = arr2.reshape(5,5)
matrix3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
matrix4 = np.delete(matrix3, [0,4], axis =0)
matrix4

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
matrix5 =np.delete(matrix4,[0,4],1)
matrix5

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])